# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ImageVectorisator
                                 A QGIS plugin
 Plugin for image vectorisation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-06
        copyright            : (C) 2023 by Euk0r
        email                : gekalets2014@yandex.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ImageVectorisator class from file ImageVectorisator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .image_vectorisator import ImageVectorisator
    return ImageVectorisator(iface)
